version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile

    mem_limit: 512M
    cpus: 0.5
    mem_reservation: 256M
    memswap_limit: 512M
    mem_swappiness: 0

    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 1m

    image: php:8.1-fpm
    restart: always
    volumes:
      - ./app:/var/www/app

    environment:
      PHP_OPCACHE: 1
      PHP_ERROR_REPORTING: E_ALL
      PHP_DISPLAY_ERRORS: 1

    networks:
      - app_net

  nginx:
    image: nginx:latest
    restart: always
    mem_limit: 512M
    cpus: 0.5

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx/sites:/etc/nginx/conf.d
      - ./react:/var/www/react
    depends_on:
      - php
      - mysql
    networks:
      - app_net
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    networks:
      - app_net

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_net

  redis-cache:
    image: redis:latest
    restart: always
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

